version: '3.9'
services:
  db_api:
    image: mongo
    restart: always
    container_name: db_api
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./data/.env
    networks:
      - net-database
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db_api
    networks:
      - net-database
      - net-front
  front:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/usr/src/app
    networks:
      - net-front
networks:
  net-database:
    driver: bridge
  net-front: